core:
  command-aliases: gp,gamepoints,points,coins
  lang: en
  prefix: 'GamePoints'

data:
  auto-save: 15
  storage:
    type: sqlite
    username: none
    password: none
    host: none
    database: none
  purge:
    enabled: false
    days: 60

general:
  start-balance: 0
  top-update-time: 20

store:
  title: Points Store
  size: 9
  transaction-logs:
    format: '[%date%] %player% bought %product% in %store% store for %price% points.'
    date: 'dd/MM/yyyy HH:mm:ss'
    console:
      enabled: true
    file:
      enabled: true
  stores:
    ranks:
      name: '&b&lRanks'
      material: 'DIAMOND'
      lore:
      - '&7Buy ranks here!'
      slots: 4
  content:
    filler:
      material: BLACK_STAINED_GLASS_PANE
      name: '&7'
      slots: 0,1,2,3,5,6,7,8
